<a href="https://colab.research.google.com/github/annaannaR/machine-learning-bootcamp/blob/main/Projekt_Ko%C5%84cowy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import csv
from io import StringIO

# make sure that plots are visible in this notebook
%matplotlib inline

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import pandas as pd
import csv
from io import StringIO
import unicodedata

sheets = pd.read_excel("Vivino-export.xlsx", engine="openpyxl", sheet_name=None)

dfs = []

for sheet_name, df_raw in sheets.items():
    if df_raw.empty:
        continue

    text = "\n".join(df_raw.iloc[:, 0].dropna().astype(str))

    df_part = pd.read_csv(
        StringIO(text),
        sep=",",
        engine="python",
        quoting=csv.QUOTE_MINIMAL,
        on_bad_lines="skip"
    )

    df_part.columns = ["name", "country", "region", "rating", "rating_count", "price"]
    df_part["sheet"] = sheet_name
    dfs.append(df_part)

df = pd.concat(dfs, ignore_index=True)

def normalize_text(text):
    text = unicodedata.normalize('NFKD', text)
    return text.encode('ascii', 'ignore').decode('utf-8')

for col in ["name", "country", "region"]:
    df[col] = df[col].apply(lambda x: normalize_text(x) if isinstance(x, str) else x)

df.head()

,name,country,region,rating,rating_count,price,sheet
0,Caiarossa Aria di Caiarossa 2015,"('Itali ',)","('Toscane',)",4.2,506,28.047878,Italie
1,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali ',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie
3,Caiarossa Aria di Caiarossa 2015,"('Itali ',)","('Toscane',)",4.2,504,28.088608,Uruguay
4,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.302771,Uruguay

In [22]:
df

,name,country,region,rating,rating_count,price,sheet
0,Caiarossa Aria di Caiarossa 2015,"('Itali ',)","('Toscane',)",4.2,506,28.047878,Italie
1,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali ',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie
3,Caiarossa Aria di Caiarossa 2015,"('Itali ',)","('Toscane',)",4.2,504,28.088608,Uruguay
4,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.302771,Uruguay
...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,"('Chili',)","('Valle del Loncomilla',)",3.4,235,11.577249,New Zealand
409738,Vergelegen Sauvignon Blanc 2019,"('Zuid-Afrika',)","('Stellenbosch',)",3.6,145,21.419927,New Zealand
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,"('Zuid-Afrika',)","('Stellenbosch',)",4.0,145,21.419927,New Zealand
409740,Clearwater Cove Sauvignon Blanc Ros 2020,"('New Zealand',)","('Marlborough',)",3.9,111,13.029447,New Zealand
409741,Clearwater Cove Pinot Grigio (Gris) 2020,"('New Zealand',)","('Marlborough',)",4.0,79,13.029447,New Zealand

In [23]:
df.country.value_counts()

country
('Frankrijk',)              192868
('Itali ',)                  77366
('Spanje',)                  35600
('Australi ',)               31138
('Portugal',)                15415
('Verenigde Staten',)        13154
('Argentini ',)              12099
('Chili',)                   11500
('Duitsland',)                4718
('New Zealand',)              4681
('Zuid-Afrika',)              3064
('Oostenrijk',)               2786
('Brazili ',)                 1452
('Libanon',)                  1178
('Uruguay',)                   604
('Griekenland',)               515
('Canada',)                    480
('Armeni ',)                   384
('Hongarije',)                 258
('Verenigd Koninkrijk',)       142
('Moldavi ',)                  114
('Georgi ',)                    48
('Mexico',)                     34
('Luxembourg',)                 34
('Serbia',)                     24
('Isra l',)                     21
('Marokko',)                    12
('Slowakije',)                  12
('Roemeni ',)                   12
('Kroati ',)                    12
('Noord-Macedoni ',)             7
('Syri ',)                       3
('Rusland',)                     3
('Montenegro',)                  2
('Bulgarije',)                   2
Name: count, dtype: int64

In [24]:
df.country = df.country.astype(str).str.replace(r"[()'√´,]","", regex=True)
df.region = df.region.astype(str).str.replace(r"[()'√´,]","", regex=True)
df.country = df.country.astype(str).str.replace(r"[()'√´,]","", regex=True)
df

,name,country,region,rating,rating_count,price,sheet
0,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,506,28.047878,Italie
1,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.287832,Italie
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie
3,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,504,28.088608,Uruguay
4,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.302771,Uruguay
...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand
409738,Vergelegen Sauvignon Blanc 2019,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand
409740,Clearwater Cove Sauvignon Blanc Ros 2020,New Zealand,Marlborough,3.9,111,13.029447,New Zealand
409741,Clearwater Cove Pinot Grigio (Gris) 2020,New Zealand,Marlborough,4.0,79,13.029447,New Zealand

In [25]:
df.country.value_counts()

country
Frankrijk              192868
Itali                   77366
Spanje                  35600
Australi                31138
Portugal                15415
Verenigde Staten        13154
Argentini               12099
Chili                   11500
Duitsland                4718
New Zealand              4681
Zuid-Afrika              3064
Oostenrijk               2786
Brazili                  1452
Libanon                  1178
Uruguay                   604
Griekenland               515
Canada                    480
Armeni                    384
Hongarije                 258
Verenigd Koninkrijk       142
Moldavi                   114
Georgi                     48
Mexico                     34
Luxembourg                 34
Serbia                     24
Isra l                     21
Marokko                    12
Slowakije                  12
Roemeni                    12
Kroati                     12
Noord-Macedoni              7
Syri                        3
Rusland                     3
Montenegro                  2
Bulgarije                   2
Name: count, dtype: int64

In [26]:
df.region.value_counts()

region
Grand cru Saint-amilion    20878
Champagne                  19529
Pauillac                   15857
Margaux                    13952
Saint-Estphe               12406
                           ...
New York                       1
Brachetto dAoAcqui             1
Bourgogne Mousseux             1
Maury                          1
Alsace Grand Cru               1
Name: count, Length: 753, dtype: int64

In [27]:
df["year"] = df.name.str.extract(r"(\d{4})")
df

,name,country,region,rating,rating_count,price,sheet,year
0,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,506,28.047878,Italie,2015
1,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.287832,Italie,2019
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie,2018
3,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,504,28.088608,Uruguay,2015
4,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.302771,Uruguay,2019
...,...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand,2017
409738,Vergelegen Sauvignon Blanc 2019,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand,2019
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand,2017
409740,Clearwater Cove Sauvignon Blanc Ros 2020,New Zealand,Marlborough,3.9,111,13.029447,New Zealand,2020
409741,Clearwater Cove Pinot Grigio (Gris) 2020,New Zealand,Marlborough,4.0,79,13.029447,New Zealand,2020

In [28]:
df.name = df.name.replace(r"\s*\d{4}$", "", regex=True)
df

,name,country,region,rating,rating_count,price,sheet,year
0,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,506,28.047878,Italie,2015
1,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.287832,Italie,2019
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie,2018
3,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,504,28.088608,Uruguay,2015
4,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.302771,Uruguay,2019
...,...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand,2017
409738,Vergelegen Sauvignon Blanc,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand,2019
409739,Vergelegen Cabernet Sauvignon - Merlot,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand,2017
409740,Clearwater Cove Sauvignon Blanc Ros,New Zealand,Marlborough,3.9,111,13.029447,New Zealand,2020
409741,Clearwater Cove Pinot Grigio (Gris),New Zealand,Marlborough,4.0,79,13.029447,New Zealand,2020

In [29]:
df.describe()

              rating   rating_count          price
count  409742.000000  409742.000000  409742.000000
mean        4.051672    2142.007158     159.324483
std         0.314026    7474.734178     291.520316
min         2.500000      25.000000       1.530000
25%         3.800000     343.000000      24.890000
50%         4.100000     454.000000      57.800000
75%         4.300000    1403.000000     168.750000
max         4.800000  162666.000000   12308.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409742 entries, 0 to 409741
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          409742 non-null  object
 1   country       409742 non-null  object
 2   region        409742 non-null  object
 3   rating        409742 non-null  float64
 4   rating_count  409742 non-null  int64
 5   price         409742 non-null  float64
 6   sheet         409742 non-null  object
 7   year          360375 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 25.0+ MB

In [31]:
# df['non_vintage'] = df.apply(lambda row: 1 if row['year'] is None else 0, axis=1)

df['non_vintage'] = df['year'].isnull().astype(int)
df

,name,country,region,rating,rating_count,price,sheet,year,non_vintage
0,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,506,28.047878,Italie,2015,0
1,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.287832,Italie,2019,0
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie,2018,0
3,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,504,28.088608,Uruguay,2015,0
4,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.302771,Uruguay,2019,0
...,...,...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand,2017,0
409738,Vergelegen Sauvignon Blanc,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand,2019,0
409739,Vergelegen Cabernet Sauvignon - Merlot,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand,2017,0
409740,Clearwater Cove Sauvignon Blanc Ros,New Zealand,Marlborough,3.9,111,13.029447,New Zealand,2020,0
409741,Clearwater Cove Pinot Grigio (Gris),New Zealand,Marlborough,4.0,79,13.029447,New Zealand,2020,0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409742 entries, 0 to 409741
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          409742 non-null  object
 1   country       409742 non-null  object
 2   region        409742 non-null  object
 3   rating        409742 non-null  float64
 4   rating_count  409742 non-null  int64
 5   price         409742 non-null  float64
 6   sheet         409742 non-null  object
 7   year          360375 non-null  object
 8   non_vintage   409742 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 28.1+ MB

In [33]:
df.describe()

              rating   rating_count          price    non_vintage
count  409742.000000  409742.000000  409742.000000  409742.000000
mean        4.051672    2142.007158     159.324483       0.120483
std         0.314026    7474.734178     291.520316       0.325526
min         2.500000      25.000000       1.530000       0.000000
25%         3.800000     343.000000      24.890000       0.000000
50%         4.100000     454.000000      57.800000       0.000000
75%         4.300000    1403.000000     168.750000       0.000000
max         4.800000  162666.000000   12308.000000       1.000000

#Analiza danych

In [34]:
pd.set_option('display.max_rows', None)
df.name.value_counts()

name
Chteau Rieussec Sauternes (Premier Grand Cru Class)                                                       4703
Chteau Calon-Sgur Saint-Estphe (Grand Cru Class)                                                          4685
Chteau Latour Grand Vin Pauillac (Premier Grand Cru Class)                                                4660
Chteau Margaux Pavillon Rouge du Chteau Margaux                                                           4587
Gaja Sito Moresco Langhe                                                                                  4537
Paul Jaboulet An Hermitage La Chapelle Rouge                                                              4525
Donnafugata Ben Ry Passito di Pantelleria                                                                 4514
Chteau Mouton Rothschild Le Petit Mouton de Mouton Rothschild Pauillac                                    4499
Chteau Meyney Saint-Estphe                                                                                4465
Chteau Grand Mayne Saint-amilion Grand Cru (Grand Cru Class)                                              4459
Ceretto Barolo Brunate                                                                                    4445
Zonin Montepulciano D'Abruzzo                                                                             4443
Chteau de Fieuzal L'Abeille de Fieuzal Pessac-Lognan                                                      4439
Clos de l'Oratoire Saint-amilion Grand Cru (Grand Cru Class)                                              4439
Chteau Marquis d'Alesme Margaux (Grand Cru Class)                                                         4438
Clos Rougeard Saumur Champigny                                                                            4438
Chteau Clement-Pichon Haut-Mdoc                                                                           4433
Dominique Piron Morgon Cte du Py                                                                          4424
Chteau Bard La Chapelle Saint-amilion Grand Cru                                                           4421
Chteau Doisy-Da ne Barsac (Grand Cru Class)                                                               4421
Les Jamelles Merlot                                                                                       4421
Chteau Franc Le Maine Saint-amilion Grand Cru                                                             4421
Mas de Libian Khayym                                                                                      4421
N1 de Dourthe Sauvignon Blanc Bordeaux                                                                    4421
Baron Philippe de Rothschild Mapu Reserva Chardonnay                                                      3197
Penfolds Bin 707 Cabernet Sauvignon                                                                       2412
Mount Mary Quintet                                                                                        2352
nkonomierat Rebholz Riesling Trocken                                                                      2280
Produttori del Barbaresco Barbaresco Riserva Montefico                                                    2280
Vincent Dauvissat Va=llons Chabl=s 1er Cru                                                                2280
Ata Rangi Crimson Pinot Noir                                                                              2271
Weingut Brondlmayer Riesling Terrassen                                                                    2268
Domaine Trapet Chambertin Grand Cru                                                                       2268
Grant Burge Petite Bubbles N.V.                                                                           2268
Cantine Lavorata Greco Nero                                                                               2268
Alessandro e Gian Natale Fantino Barolo (Cascina Dardi)                                                   2268
Little Giant Malbec                                                                                       2268
Mas des Bressades Cuve Tradition Costires de Nmes Ros                                                     2268
Grant Burge Nebu Cabernet - Shiraz                                                                        2268
Oliver's Taranga Shiraz                                                                                   2268
Hardys Thomas Hardy Cabernet Sauvignon                                                                    2268
Yves Cuilleron Viognier Les Vignes d' Ct                                                                  2268
Domaine de la Grenaudire Muscadet Sevre-et-Maine Sur Lie                                                  2268
Saltram Pepperjack Cabernet Sauvignon                                                                     2268
Domaine Jean Grivot Nuits-St-Georges Aux Lavires                                                          2268
Le Salette Amarone della Valpolicella Classico                                                            2268
Yalumba Y Series Riesling                                                                                 2268
Villamedoro Pecorino                                                                                      2268
Vasse Felix Heytesbury Chardonnay                                                                         2268
Chteau l'Eglise-Clinet Pomerol                                                                            2268
Vigneti del Salento Malvasia Nera Zolla                                                                   1236
Familia Torres Mas La Plana Cabernet Sauvignon                                                             989
Chteau Musar Rouge (Gaston Hochar)                                                                         968
Baron de Ley Finca Monasterio Rioja                                                                        936
Familia Torres Atrium Merlot                                                                               928
Via Pomal Crianza                                                                                          923
Finca La Capilla La Capilla Crianza                                                                        918
Jean-Pierre Moueix Saint-amilion                                                                           918
Poggio Al Tesoro Solosole Vermentino                                                                       913
Alain Jaume Domaine Grand Veneur Ctes du Rhne Les Champauvins                                              909
Bodegas Cosme Palacio Glorioso Rioja Reserva                                                               909
Marqus de Riscal Sauvignon Blanc                                                                           909
Morca Garnacha                                                                                             906
Ferrer Bobet Priorat Vinyes Velles                                                                         906
Peter Jakob Kohn Quarzit Riesling Trocken                                                                  906
Maubrac Gurin Chateau Palene Bordeaux                                                                      906
Henri Giraud MV                                                                                            906
Calvet Fitou                                                                                               906
Castello d'Alba Douro Vinhas Velhas Grande Reserva                                                         906
Jos Pariente Verdejo Fermentado en Barrica                                                                 906
Bodegas Mano a Mano Venta La Ossa Syrah                                                                    906
Yllera Jess Yllera Crianza                                                                                 906
Croft Tawny Port 20 Year Old N.V.                                                                          906
Jeromin Flix Mart=nez Cepas Viejas                                                                         906
Puerta Vieja Crianza                                                                                       906
Melini San Lorenzo Chianti                                                                                 906
MVSA de Vallformosa Cava Brut Nature N.V.                                                                  906
Chteau Mouton Rothschild Pauillac (Premier Grand Cru Class)                                                849
Chteau Pontet-Canet Pauillac (Grand Cru Class)                                                             728
Chteau Lynch-Bages Pauillac (Grand Cru Class)                                                              657
Chteau Cantemerle Haut-Mdoc (Grand Cru Class)                                                              613
Chteau Talbot Saint-Julien (Grand Cru Class)                                                               599
Ptrus Pomerol                                                                                              599
Chteau Rauzan-Sgla Margaux (Grand Cru Class)                                                               593
Tenuta San Guido Sassicaia                                                                                 568
Chteau Beychevelle Saint-Julien (Grand Cru Class)                                                          524
Chteau Lafite Rothschild Pauillac (Premier Grand Cru Class)                                                500
Chteau Durfort-Vivens Margaux (Grand Cru Class)                                                            500
Chteau Margaux Chteau Margaux (Premier Grand Cru Class)                                                    458
Chteau Loville Poyferr Saint-Julien (Grand Cru Class)                                                      452
Chteau Olivier Pessac-Lognan (Grand Cru Class)                                                             451
Chteau Loville Barton Saint-Julien (Grand Cru Class)                                                       451
Chteau d'Yquem Sauternes                                                                                   448
Tommasi Amarone della Valpolicella Classico                                                                430
Cloudy Bay Sauvignon Blanc                                                                                 430
Louis Roederer Cristal Brut Champagne (Millsim)                                                            411
Chteau l'avangile Pomerol                                                                                  409
Chteau Sociando-Mallet Haut-Mdoc                                                                           407
Nicolas Joly Clos de la Coule de Serrant                                                                   402
Chteau Peyrabon Chteau La Fleur Peyrabon Pauillac                                                          397
Domaine de Beaurenard Chteauneuf-du-Pape                                                                   394
MAN Chenin Blanc (Free-Run Steen)                                                                          394
Chteau Gloria Saint-Julien                                                                                 392
Chteau Montrose Saint-Estphe (Grand Cru Class)                                                             391
Dom Prignon Brut Champagne                                                                                 389
Paul Jaboulet An Crozes-Hermitage Domaine de Thalabert                                                     384
Zorah Karas                                                                                                384
Chteau Pichon Longueville Comtesse de Lalande Pauillac (Grand Cru Class)                                   382
Chteau Taillefer Pomerol                                                                                   380
Chteau Lafon-Rochet Les Plerins de Lafon-Rochet Saint-Estphe                                               377
Chteau Loville Las Cases Saint-Julien (Grand Cru Class)                                                    376
Cos d'Estournel Cos d'Estournel                                                                            375
Chteau Duhart-Milon Pauillac (Grand Cru Class)                                                             374
Chteau Haut Prieur Blaye - Ctes de Bordeaux                                                                372
Antinori Tignanello                                                                                        370
Tenuta San Guido Guidalberto                                                                               370
Veuve Clicquot Brut (Carte Jaune) Champagne N.V.                                                           368
Ornellaia Le Volte                                                                                         366
Chteau Pichon Baron Pauillac (Grand Cru Class)                                                             363
Chteau Giscours Chteau Giscours (Grand Cru Class)                                                          361
Castelnau Blanc de Blancs Millesim Brut Champagne                                                          360
Champagne de Saint-Gall Orpale Blanc de Blancs Brut Champagne Grand Cru                                    360
Olim Bauda Le Rocchette Barbera d'Asti Superiore                                                           360
Charles Mignon Cuve Comte de Marne Ros Brut Grand Cru Champagne N.V.                                       360
Deutz Cuve William Deutz Millesim Brut Champagne                                                           360
Mavrio Negroamaro                                                                                          360
Domaine de la Janasse Chteauneuf-du-Pape Chaupin                                                           360
Chteau Doisy-Da ne Bordeaux Blanc Sec                                                                      360
Marc Kreydenweiss Kritt Pinot Blanc                                                                        360
Mo t & Chandon Imprial Brut Champagne N.V.                                                                 358
Marqus de Riscal Rioja Reserva                                                                             357
Bollinger Special Cuve Brut A Champagne N.V.                                                               355
Chteau d'Armailhac Pauillac (Grand Cru Class)                                                              355
Opus One Opus One                                                                                          353
Ornellaia Le Serre Nuove                                                                                   353
Chteau Pape Clment Pessac-Lognan (Grand Cru Class de Graves)                                               343
Penfolds Bin 389 Cabernet - Shiraz                                                                         339
Chteau Lagrange Saint-Julien (Grand Cru Class)                                                             335
Pol Roger Rserve Brut Champagne N.V.                                                                       335
Pintia Toro                                                                                                335
Chteau Chasse-Spleen Moulis-en-Mdoc                                                                        330
Chteau Haut-Brion Pessac-Lognan (Premier Grand Cru Class)                                                  320
Billecart-Salmon Brut Ros Champagne N.V.                                                                   318
Taittinger Brut (Rserve) Champagne N.V.                                                                    313
Tenuta San Guido Le Difese                                                                                 312
Perrier-Jou t Grand Brut Champagne N.V.                                                                    310
Chteau Smith Haut-Lafitte Pessac-Lognan (Grand Cru Class de Graves)                                        298
Chteau d'Esclans Whispering Angel Ros                                                                      297
Antinori Villa Antinori Rosso                                                                              291
E. Guigal Ctes-du-Rhne Rouge                                                                               291
Minuty M Ros                                                                                               283
Billecart-Salmon Brut Rserve Champagne N.V.                                                                282
Laurent-Perrier La Cuve Brut Champagne N.V.                                                                282
Chteau de Beaucastel Chteauneuf-du-Pape                                                                    278
R. Lpez de Heredia Via Tondonia Reserva                                                                    276
Deutz Classic Brut Champagne N.V.                                                                          276
Ruinart Brut Ros Champagne N.V.                                                                            270
Laurent-Perrier Brut Cuve Champagne Ros N.V.                                                               270
Ruinart Brut (R de Ruinart) Champagne N.V.                                                                 269
Boekenhoutskloof The Chocolate Block                                                                       268
Chteau Branaire-Ducru Saint-Julien (Grand Cru Class)                                                       265
Vega Sicilia Unico                                                                                         260
Catena Malbec                                                                                              259
Chteau Montrose La Dame de Montrose Saint-Estphe                                                           259
Chteau Lascombes Margaux (Grand Cru Class)                                                                 258
Castello Nipozzano Chianti Rfina Riserva                                                                   258
Chteau Ormes de Pez Saint-Estphe                                                                           257
Tenuta Luce Lucente                                                                                        255
Domaine de Chevalier Pessac-Lognan (Grand Cru Class de Graves)                                             254
Penfolds Bin 28 Shiraz                                                                                     253
Ruinart Blanc de Blancs Brut Champagne N.V.                                                                253
Farnese Edizione Cinque Autoctoni N.V.                                                                     252
Catena Alta Malbec                                                                                         251
Charles Heidsieck Brut Rserve N.V.                                                                         250
Mo t & Chandon Imprial Ros Brut Champagne N.V.                                                             249
Chteau Lafon-Rochet Saint-Estphe (Grand Cru Class)                                                         247
Louis Roederer Brut Premier Champagne N.V.                                                                 247
Chteau La Tour Carnet Haut-Mdoc (Grand Cru Class)                                                          245
G.H. Mumm (Cordon Rouge) Brut Champagne N.V.                                                               244
Ornellaia Bolgheri Superiore                                                                               243

In [35]:
df.groupby('name')['rating'].mean().sort_values(ascending=False).head(10)

name
Darioush Darius II Cabernet Sauvignon                            4.800000
Domaine de La Romane-Conti La Tche Grand Cru                     4.800000
Toro Albal Don PX Convento Seleccin                              4.800000
Vega Sicilia Unico Reserva Especial Edicin                       4.750000
Giacomo Conterno Barolo Cascina Francia                          4.750000
Quintarelli Giuseppe Amarone della Valpolicella Classico         4.725000
Chteau d'Yquem Sauternes                                         4.704911
Vega Sicilia Unico                                               4.702692
Marqus de Murrieta Castillo Ygay Gran Reserva Especial Blanco    4.700000
Harlan Estate Harlan Estate Red                                  4.700000
Name: rating, dtype: float64

In [36]:
df.groupby('region')['rating'].agg(['mean', 'count']).head(20)

                                              mean  count
region
"Beaune 1er Cru Les Grves"                4.438462     39
"Chablis 1er Cru Butteaux"                4.600000     12
"Chablis 1er Cru Cte de Lechet"           4.200000     12
"Chablis 1er Cru Fourchaume"              4.150000      6
"Chablis 1er Cru Montee de Tonnerre"      4.600000     12
"Chablis 1er Cru Montmains"               4.200000     12
"Chablis 1er Cru Vaillons"                4.200524   2292
"Chablis Grand Cru Bougros"               4.200000     12
"Chablis Grand Cru Grenouilles"           4.400000      3
"Chablis Grand Cru Les Clos"              4.200000     12
"Champagne Grand Cru A"                   4.465366   1025
"Champagne Grand Cru Ambonnay"            4.281140    228
"Champagne Grand Cru Avize"               4.260465    301
"Champagne Grand Cru Bouzy"               4.060406    394
"Champagne Grand Cru Chouilly"            3.886142    267
"Champagne Grand Cru Cramant"             4.027723    101
"Champagne Grand Cru Le Mesnil-sur-Oger"  4.006723    476
"Champagne Grand Cru Verzy"               4.094444     18
"Costa dAmalfi"                           4.400000      3
"Coteaux dAix-en-Provence"                4.043056    144