<a href="https://colab.research.google.com/github/annaannaR/machine-learning-bootcamp/blob/main/final_project/FinalProjectAmsterdamDataAcademy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from io import StringIO

%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
sheets = pd.read_excel('/content/Vivino-export.xlsx', sheet_name=None, header=None, engine="openpyxl")

dfs = []
for sheet, raw in sheets.items():
    if raw.empty:
        continue

    text = "\n".join(raw.iloc[:, 0].dropna().astype(str))

    part = pd.read_csv(StringIO(text), sep=",", engine="python", on_bad_lines="skip")

    part.columns = ["name", "country", "region", "rating", "rating_count", "price"]
    part["sheet"] = sheet
    dfs.append(part)

df = pd.concat(dfs, ignore_index=True)
df.head()

,name,country,region,rating,rating_count,price,sheet
0,Tenuta San Guido Sassicaia 2019,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,1006,323.795972,Italie
1,Caiarossa Aria di Caiarossa 2015,"('Itali√´',)","('Toscane',)",4.2,506,28.047878,Italie
2,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie
3,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali√´',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie
4,Tenuta San Guido Sassicaia 2019,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,983,324.266172,Uruguay

In [ ]:
df["year"] = df.name.str.extract(r"(\d{4})")
df

,name,country,region,rating,rating_count,price,sheet,year
0,Tenuta San Guido Sassicaia 2019,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,1006,323.795972,Italie,2019
1,Caiarossa Aria di Caiarossa 2015,"('Itali√´',)","('Toscane',)",4.2,506,28.047878,Italie,2015
2,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie,2019
3,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali√´',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie,2018
4,Tenuta San Guido Sassicaia 2019,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,983,324.266172,Uruguay,2019
...,...,...,...,...,...,...,...,...
409753,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,"('Chili',)","('Valle del Loncomilla',)",3.4,235,11.577249,New Zealand,2017
409754,Vergelegen Sauvignon Blanc 2019,"('Zuid-Afrika',)","('Stellenbosch',)",3.6,145,21.419927,New Zealand,2019
409755,Vergelegen Cabernet Sauvignon - Merlot 2017,"('Zuid-Afrika',)","('Stellenbosch',)",4.0,145,21.419927,New Zealand,2017
409756,Clearwater Cove Sauvignon Blanc Ros√© 2020,"('New Zealand',)","('Marlborough',)",3.9,111,13.029447,New Zealand,2020
409757,Clearwater Cove Pinot Grigio (Gris) 2020,"('New Zealand',)","('Marlborough',)",4.0,79,13.029447,New Zealand,2020

In [ ]:
df.name = df.name.replace(r"\s*\d{4}$", "", regex=True)
df

,name,country,region,rating,rating_count,price,sheet,year
0,Tenuta San Guido Sassicaia,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,1006,323.795972,Italie,2019
1,Caiarossa Aria di Caiarossa,"('Itali√´',)","('Toscane',)",4.2,506,28.047878,Italie,2015
2,Martin Tesch Unplugged Riesling,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie,2019
3,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali√´',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie,2018
4,Tenuta San Guido Sassicaia,"('Itali√´',)","('Bolgheri Sassicaia',)",4.6,983,324.266172,Uruguay,2019
...,...,...,...,...,...,...,...,...
409753,Cremaschi Furlotti Cabernet Sauvignon Reserva,"('Chili',)","('Valle del Loncomilla',)",3.4,235,11.577249,New Zealand,2017
409754,Vergelegen Sauvignon Blanc,"('Zuid-Afrika',)","('Stellenbosch',)",3.6,145,21.419927,New Zealand,2019
409755,Vergelegen Cabernet Sauvignon - Merlot,"('Zuid-Afrika',)","('Stellenbosch',)",4.0,145,21.419927,New Zealand,2017
409756,Clearwater Cove Sauvignon Blanc Ros√©,"('New Zealand',)","('Marlborough',)",3.9,111,13.029447,New Zealand,2020
409757,Clearwater Cove Pinot Grigio (Gris),"('New Zealand',)","('Marlborough',)",4.0,79,13.029447,New Zealand,2020

In [ ]:
BAD_CHARS = r"[()'`,√´©¢®¬∞≠∫Æ¨±¥Äô]"

In [ ]:
names_to_clean = ["country", "region", "name"]

for naam in names_to_clean:
    df[naam] = (df[naam].astype(str).str.replace(BAD_CHARS, "", regex=True).str.strip())

In [ ]:
df.sample(50)

,name,country,region,rating,rating_count,price,sheet,year
256586,Opus One Opus One,Verenigde Staten,Napa Valley,4.7,2437,429.000000,Serbia,2017
266350,Quinta do Monte dOiro Reserva,Portugal,Lisboa,4.2,179,627.360000,Hongarije,2015
365720,Delheim Sauvignon Blanc,Zuid-Afrika,Stellenbosch,3.7,31,6.243319,Portugal,2022
357367,Chteau de Fieuzal LAbeille de Fieuzal Pessac-L...,Frankrijk,Pessac-Lognan,3.9,455,27.800000,Portugal,2013
390023,Ata Rangi Crimson Pinot Noir,New Zealand,Martinborough,3.8,111,40.000000,New Zealand,2020
403020,Chteau Meyney Saint-Estphe,Frankrijk,Saint-Estphe,4.0,456,68.000000,New Zealand,2000
317851,Whitehaven Sauvignon Blanc,New Zealand,Marlborough,4.0,115,29.990000,Libanon,2022
74580,Dominique Piron Morgon Cte du Py,Frankrijk,Morgon,3.8,454,17.000000,Chili,2017
303692,Donnafugata Ben Ry Passito di Pantelleria,Itali,Passito di Pantelleria,4.4,455,60.000000,Duitsland,2020
73307,Les Jamelles Merlot,Frankrijk,"""Pays dOc""",3.6,453,15.750000,Chili,2018
362402,Klein Constantia Vin de Constance Natural Sweet,Zuid-Afrika,Constantia,4.7,1381,99.000000,Portugal,2015
112672,El Coto Crianza,Spanje,Rioja Alavesa,3.7,2545,6.210000,Spanje,2018
46083,Jean-Pierre Moueix Saint-âmilion,Frankrijk,Saint-âmilion,3.7,343,21.010000,Uruguay,2018
223562,Mas des Bressades Cuve Tradition Costires de N...,Frankrijk,Costires-de-Nmes,3.6,109,28.990000,Serbia,2020
28609,Le Macchiole Bolgheri Rosso,Itali,Bolgheri,4.1,2221,25.300000,Uruguay,2017
124144,Catena Zapata Adrianna Vineyard River Stones M...,Argentini,Mendoza,4.7,173,239.990000,Argentinie,2018
108032,Chteau Rauzan-Sgla Margaux Grand Cru Class,Frankrijk,Margaux,4.3,437,130.000000,Spanje,2015
30300,Chteau Smith Haut-Lafitte Pessac-Lognan Blanc,Frankrijk,Pessac-Lognan,4.5,457,266.500000,Uruguay,2015
47903,Castello dAlba Douro Vinhas Velhas Grande Reserva,Portugal,Douro,4.1,340,38.990000,Uruguay,2017
161031,Zonin Montepulciano DAbruzzo,Itali,Montepulciano d‚Abruzzo,3.4,450,11.900000,Griekenland,2020
146206,Chteau Grand-Puy-Lacoste Lacoste Borie Pauillac,Frankrijk,Pauillac,3.9,566,688.700000,Griekenland,2013
158391,Dominique Piron Morgon Cte du Py,Frankrijk,Morgon,3.8,454,17.000000,Griekenland,2017
252785,Marqus de Murrieta Reserva Rioja Finca Ygay,Spanje,Rioja,4.2,3800,279.844214,Serbia,2017
340470,Cantine Lavorata Greco Nero,Itali,Calabri,4.1,110,49.480000,Portugal,2016
360519,Joseph Perrier Brut Champagne Cuve Royale N.V.,Frankrijk,Champagne,3.9,9078,34.500000,Portugal,NaN
105431,Luca Old Vine Malbec,Argentini,Valle de Uco,4.3,2646,223.000000,Spanje,2017
304180,Mas de Libian Khayym,Frankrijk,Ctes du Rhne,3.8,452,15.600000,Duitsland,2020
347121,Chteau Smith Haut-Lafitte Pessac-Lognan Grand ...,Frankrijk,Pessac-Lognan,4.4,1590,225.200000,Portugal,2010
118544,Little Giant Malbec,Australi,Zuid-Australi,3.9,110,17.000000,Argentinie,2021
381889,Peter Jakob Kºhn Quarzit Riesling Trocken,Duitsland,Rheingau,4.0,343,25.140000,Portugal,2018
87994,Ferrari Carano Cabernet Sauvignon,Verenigde Staten,Alexander Valley,4.0,519,55.890000,Spanje,2015
230968,Espor£o Espor£o Reserva Tinto,Portugal,Alentejo,4.2,2922,175.000000,Serbia,2019
364920,Chteau Durfort-Vivens Margaux Grand Cru Class,Frankrijk,Margaux,4.0,436,85.000000,Portugal,2006
49399,Altesino Brunello di Montalcino,Itali,Brunello di Montalcino,4.2,1479,42.187137,Uruguay,2016
1368,Cloudy Bay Pinot Noir,New Zealand,Marlborough,4.1,278,60.480000,Uruguay,2020
137436,Chteau Meyney Saint-Estphe,Frankrijk,Saint-Estphe,4.0,456,68.000000,Argentinie,2000
111379,Palacios Remondo La Montesa,Spanje,Rioja,3.9,2662,640.000000,Spanje,2017
93509,Chteau Margaux Pavillon Rouge du Chteau Margaux,Frankrijk,Margaux,4.3,455,278.100000,Spanje,2007
217364,Chteau Batailley Pauillac Grand Cru Class,Frankrijk,Pauillac,4.0,1223,67.000000,Frankrijk,2006
141143,Grant Burge Petite Bubbles N.V.,Australi,Zuid-Australi,3.6,110,16.990000,Griekenland,NaN
327238,N1 de Dourthe Sauvignon Blanc Bordeaux,Frankrijk,Bordeaux,3.6,452,6.300000,Libanon,2015
375383,Croft Tawny Port 20 Year Old N.V.,Portugal,Porto,4.1,339,44.600000,Portugal,NaN
31530,Chteau Haut Prieur Blaye - Ctes de Bordeaux,Frankrijk,Blaye - Ctes de Bordeaux,4.1,439,11.900000,Uruguay,2018
212137,Bodegas Mano a Mano Venta La Ossa Syrah,Spanje,Castili,4.1,340,11.910000,Frankrijk,2018
190519,Pasqua Vigneti e Cantine PassioneSentimento Pr...,Itali,Prosecco di Treviso,3.8,2935,15.400000,Frankrijk,NaN
131691,Chteau Doisy-Dane Barsac Grand Cru Class,Frankrijk,Barsac,4.3,454,45.400000,Argentinie,2010
382532,MVSA de Vallformosa Cava Brut Nature N.V.,Spanje,Cava,3.6,340,5.500000,Portugal,NaN
391921,Ventisquero Grey Glacier Garnacha - Cariena - ...,Chili,Colchagua Valley,3.9,429,269.900000,New Zealand,2018
255402,G.H. Mumm Cordon Rouge Le Ros Brut Champagne N.V.,Frankrijk,Champagne,3.9,3117,209.000000,Serbia,NaN
137387,Chteau de Fieuzal LAbeille de Fieuzal Pessac-L...,Frankrijk,Pessac-Lognan,3.9,455,27.800000,Argentinie,2013

In [ ]:
df["price"] = pd.to_numeric(df["price"], errors="coerce").round(2)
df

,name,country,region,rating,rating_count,price,sheet,year
0,Tenuta San Guido Sassicaia,Itali,Bolgheri Sassicaia,4.6,1006,323.80,Italie,2019
1,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,506,28.05,Italie,2015
2,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.29,Italie,2019
3,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.70,Italie,2018
4,Tenuta San Guido Sassicaia,Itali,Bolgheri Sassicaia,4.6,983,324.27,Uruguay,2019
...,...,...,...,...,...,...,...,...
409753,Cremaschi Furlotti Cabernet Sauvignon Reserva,Chili,Valle del Loncomilla,3.4,235,11.58,New Zealand,2017
409754,Vergelegen Sauvignon Blanc,Zuid-Afrika,Stellenbosch,3.6,145,21.42,New Zealand,2019
409755,Vergelegen Cabernet Sauvignon - Merlot,Zuid-Afrika,Stellenbosch,4.0,145,21.42,New Zealand,2017
409756,Clearwater Cove Sauvignon Blanc Ros,New Zealand,Marlborough,3.9,111,13.03,New Zealand,2020
409757,Clearwater Cove Pinot Grigio Gris,New Zealand,Marlborough,4.0,79,13.03,New Zealand,2020